dist: xenial
services:
  - xvfb

language: java


jdk:
 - openjdk11

script:
- sudo apt-get update && sudo apt-get install openjdk11
- java -version
- mvn test

after_success:
  - bash <(curl -s https://codecov.io/bash)
